name: Deploy Quartz site to GitHub Pages

# This workflow runs on pushes to your main content branch
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Checkout the official Quartz framework to act as our base.
      - name: Checkout Quartz Framework
        uses: actions/checkout@v4
        with:
          repository: 'jackyzha0/quartz'
          ref: 'v4'

      # Step 2: Checkout your content repository into the 'content' directory.
      - name: Checkout Our Content
        uses: actions/checkout@v4
        with:
          path: content
          fetch-depth: 0

      # Step 3: Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Step 4: Install dependencies from the framework's lockfile and build
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build

      # Step 5: Upload the artifact for the deploy job
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  # Step 6: Deploy the built site to GitHub Pages
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4